### ISSUE TITLE
Find a couple of bootstrap templates that the team can look at

### ISSUE THREAD

**Issue by cfrank1977** [cfrank1977/MedTV#1]
Given that bootstrap, templates are attached to this issues.
Then the team as a whole can review each template. 
So that the team can collaboratively decide on a bootstrap template for the project. 
Team to meet 8/3/2018 to decide on a template.

**Comment by flofong** [comment]
Added to Trello board under 'in progress'  for review Friday, Aug 3 with the group.  At least a couple of suggestions for each page.
